### ISSUE TITLE
Issue with generating pre-training dataset, ShapeNetFeat

### ISSUE THREAD

**Issue by mfarazi1991** [SimingYan/MaskFeat3D#2]
Hi,

Thanks for releasing the code. I have a hard time knowing how I can generate the .npy files for the Shapenet dataset so that I can have the structure as mentioned for ShapeNetFeat. I downloaded different processed files from point-BERT, but those .npy files are different (already sampled). Can you upload a file regarding how to create this dataset? The pre-process.py is just for surface variation and it works fine. 
Thanks!

**Comment by SimingYan** [comment]
Hi,

Thanks for your interest! For the point cloud data, my suggestion is you could directly download the raw mesh data from official ShapeNet website and sample point cloud by yourself. I think our code just needs the point cloud data to be formatted as [50000, 6].
